version: '3'

services:
  multi-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "3000:3000"
      - "7005:7005"
    volumes:
      - ./git-server:/app/git-server
      - ./server:/app/server
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
